name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.60.191.95
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22
            cd /var/www/test
            git pull origin main
            npm install
            pm2 describe app > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart app --update-env
            else
              pm2 start app.js --name app
            fi
