name: Deploy to EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.60.191.95
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22
            cd /var/www/test
            git pull origin main
            npm install
            pm2 describe app > /dev/null
            if [ $? -eq 0 ]; then
              echo "Restarting existing app"
              pm2 restart app --update-env
            else
              echo "Starting new app instance"
              pm2 start app.js --name app
            fi

